# -*- coding: utf-8 -*-
"""Algorithm assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d58hOAsI1xBnCf1iEqKxmAyfNSMKZp7r
"""

#題目一
import time

def fibonacci_recursive(n):
    if n <= 1:
        return n
    else:
        return fibonacci_recursive(n-1) + fibonacci_recursive(n-2)

execution_times_recursive = []

for i in range(1, 101):
    start_time = time.time()
    fibonacci_recursive(i)
    end_time = time.time()
    execution_time = end_time - start_time
    execution_times_recursive.append(execution_time)

print(execution_times_recursive)

import time
def fibonacci_bottom_up(n):
    fib = [0, 1]
    for i in range(2, n + 1):
        fib.append(fib[i - 1] + fib[i - 2])
    return fib[n]

execution_times_bottom_up = []

for i in range(1, 101):
    start_time = time.time()
    fibonacci_bottom_up(i)
    end_time = time.time()
    execution_time = end_time - start_time
    execution_times_bottom_up.append(execution_time)

print(execution_times_bottom_up)

import matplotlib.pyplot as plt

# 設置 x 軸的數值，從 1 到 100
x_values = list(range(1, 101))

# 繪製自頂向下方法的執行時間折線圖
plt.plot(x_values, execution_times_recursive, label='Top-down (Recursive)', color='blue')

# 繪製自底向上方法的執行時間折線圖
plt.plot(x_values, execution_times_bottom_up, label='Bottom-up (Dynamic Programming)', color='red')

# 添加標題和標籤
plt.title('Execution Time of Fibonacci Numbers')
plt.xlabel('Fibonacci Number (n)')
plt.ylabel('Execution Time (seconds)')

# 添加圖例
plt.legend()

# 顯示圖形
plt.show()

#題目2
def fibonacci_recursive_with_count(n, count):
    if n == 4:
        count[0] += 1
    if n <= 1:
        return n
    else:
        return fibonacci_recursive_with_count(n-1, count) + fibonacci_recursive_with_count(n-2, count)

# F(4)次數陣列
count_f4 = [0]

# 紀錄F(4)出現次數
for i in range(5, 51):
    fibonacci_recursive_with_count(i, count_f4)

print(count_f4[0])

import matplotlib.pyplot as plt

# F(4)次數陣列
count_f4 = []

# 記錄計算 F(4）次數
for i in range(5, 51):
    count = [0]
    fibonacci_recursive_with_count(i, count)
    count_f4.append(count[0])

# 設置 x 軸的數值，從 5 到 50
x_values = list(range(5, 51))

# 繪製計算 F(4)次數的折線圖
plt.plot(x_values, count_f4, label='Count of F(4)', color='green')

plt.title('Count of F(4) During Calculation of F(5) to F(50)')
plt.xlabel('Fibonacci Number (n)')
plt.ylabel('Count of F(4)')

plt.legend()

plt.show()